# Generated by Django 3.2.4 on 2021-07-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default=None, max_length=225)),
                ('created_at', models.CharField(default=None, max_length=225)),
                ('update_at', models.CharField(default=None, max_length=225)),
                ('created_by', models.CharField(default=None, max_length=225)),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
    ]
